# bind the cert-manager internal approver to approve
# adcs.certmanager.csf.nokia.com CertificateRequests
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-controller-approve:adcs-certmanager-csf-nokia-com
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-controller-approve:adcs-certmanager-csf-nokia-com
subjects:
- kind: ServiceAccount
  name: cert-manager
  namespace: cert-manager
