
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: adcsrequests.adcs.certmanager.csf.nokia.com
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.status.State
    name: State
    type: string
  group: adcs.certmanager.csf.nokia.com
  names:
    kind: AdcsRequest
    listKind: AdcsRequestList
    plural: adcsrequests
    singular: adcsrequest
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: AdcsRequest is the Schema for the adcsrequests API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: AdcsRequestSpec defines the desired state of AdcsRequest
          properties:
            csr:
              description: Certificate signing request bytes in PEM encoding. This
                will be used when finalizing the request. This field must be set on
                the request.
              format: byte
              type: string
            issuerRef:
              description: IssuerRef references a properly configured AdcsIssuer which
                should be used to serve this AdcsRequest. If the Issuer does not exist,
                processing will be retried. If the Issuer is not an 'ADCS' Issuer,
                an error will be returned and the ADCSRequest will be marked as failed.
              properties:
                group:
                  type: string
                kind:
                  type: string
                name:
                  type: string
              required:
              - name
              type: object
          required:
          - csr
          - issuerRef
          type: object
        status:
          description: AdcsRequestStatus defines the observed state of AdcsRequest
          properties:
            id:
              description: ID of the Request assigned by the ADCS. This will initially
                be empty when the resource is first created. The ADCSRequest controller
                will populate this field when the Request is accepted by ADCS. This
                field will be immutable after it is initially set.
              type: string
            reason:
              description: Reason optionally provides more information about a why
                the AdcsRequest is in the current state.
              type: string
            state:
              description: State contains the current state of this ADCSRequest resource.
                States 'ready' and 'rejected' are 'final'
              enum:
              - pending
              - ready
              - errored
              - rejected
              type: string
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
