
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: adcsissuers.adcs.certmanager.csf.nokia.com
spec:
  group: adcs.certmanager.csf.nokia.com
  names:
    kind: AdcsIssuer
    listKind: AdcsIssuerList
    plural: adcsissuers
    singular: adcsissuer
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: AdcsIssuer is the Schema for the adcsissuers API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: AdcsIssuerSpec defines the desired state of AdcsIssuer
          properties:
            caBundle:
              description: CABundle is a PEM encoded TLS certifiate to use to verify
                connections to the ADCS server.
              format: byte
              type: string
            credentialsRef:
              description: CredentialsRef is a reference to a Secret containing the
                username and password for the ADCS server. The secret must contain
                two keys, 'username' and 'password'.
              properties:
                name:
                  description: Name of the referent.
                  type: string
              required:
              - name
              type: object
            retryInterval:
              description: How often to retry in case of communication errors (in
                time.ParseDuration() format) Default 1 hour.
              type: string
            statusCheckInterval:
              description: How often to check for request status in the server (in
                time.ParseDuration() format) Default 6 hours.
              type: string
            url:
              description: URL is the base URL for the ADCS instance
              type: string
          required:
          - credentialsRef
          - url
          type: object
        status:
          description: AdcsIssuerStatus defines the observed state of AdcsIssuer
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
